# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define :latin do |latin|
    latin.vm.hostname = "latin"
    latin.vm.network :private_network, ip: "192.168.55.10"
  end

  config.vm.define :crack do |crack|
    crack.vm.hostname = "crack"
    crack.vm.network :private_network, ip: "192.168.55.11"
  end
end
