# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define :morph do |morph|
    morph.vm.hostname = "morph"
    morph.vm.network :private_network, ip: "192.168.55.40"
  end

  config.vm.define :flute do |flute|
    flute.vm.hostname = "flute"
    flute.vm.network :private_network, ip: "192.168.55.41"
  end
end
