# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "szops/centos-6-x86_64"

  config.vm.define :balsa do |balsa|
    balsa.vm.hostname = "balsa"
    balsa.vm.network :private_network, ip: "192.168.55.30"
  end

  config.vm.define :benny do |benny|
    benny.vm.hostname = "benny"
    benny.vm.network :private_network, ip: "192.168.55.31"
  end
end
