#Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
- name: install selinux bindings
  yum: name=libselinux-python state=present
  changed_when: false
  tags:
    - vagrant

- name: Install package for Oracle Linux / RHEL / CentOS
  yum:
    name={{vagrant_tmp_file}} state=present
  changed_when: false
  tags:
    - vagrant

# Oracle Linux / RHEL / CentOS
- name: Adding virtualbox repository into sources list for Oracle Linux / RHEL / CentOS
  template: src=RHEL.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
  tags:
    - vagrant

- name: Install epel-release packages
  yum:
    name: epel-release
    state: 'present'
    update_cache: yes

- name: Install Development and tools packages
  yum:
    name: "@development"
    state: 'present'
    update_cache: yes

- name: Install kernel_devel packages
  yum:
    name: kernel-devel
    state: 'present'
    update_cache: yes

- name: Install VirtualBox
  yum: 
    name: "{{ virtualbox_package }}"
    state:  'present'
    update_cache: yes
