# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = false
    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end

# Uncommented are Tested
  config.vm.define :centos7 do |centos7|
    centos7.vm.box = "relativkreativ/centos-7-minimal"
  end

#  config.vm.define :centos6 do |centos6|
#    centos6.vm.box = "bento/centos-6.7"
#  end

#  config.vm.define :fedora21 do |fedora21|
#    fedora21.vm.box = "bento/fedora-21"
#  end

#  config.vm.define :fedora22 do |fedora22|
#    fedora22.vm.box = "bento/fedora-22"
#  end

#  config.vm.define :opensuse_132_x86_64 do |opensuse132x64|
#    opensuse132x64.vm.box = "bento/opensuse-13.2-x86_64"
#  end

#  config.vm.define :precise64 do |precise64|
#    precise64.vm.box = "hashicorp/precise64"
#  end

#  config.vm.define :ubuntu_1404_x64 do |ubuntu_1404_x64|
#    ubuntu_1404_x64.vm.box = "bento/ubuntu-14.04"
#  end

#  config.vm.define :ubuntu_1504_i386 do |ubuntu_1504_i386|
#    ubuntu_1504_i386.vm.box = "bento/ubuntu-15.04-i386"
#  end

#  config.vm.define :ubuntu_1504_x64 do |ubuntu_1504_x64|
#    ubuntu_1504_x64.vm.box = "bento/ubuntu-15.04"
#  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    #ansible.verbose = "vvv"
  end
end
