# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "jasonish/centos5-x64-minimal"

  config.vm.define :charm do |charm|
    charm.vm.hostname = "charm"
    charm.vm.network :private_network, ip: "192.168.55.20"
  end

  config.vm.define :shelf do |shelf|
    shelf.vm.hostname = "shelf"
    shelf.vm.network :private_network, ip: "192.168.55.21"
  end
end
