---
- name: Provision virtualbox host
  user: root
  hosts: control
  vars:
    virtualbox_repo_key: "http://www.virtualbox.org/download/oracle_vbox.asc"

  tasks:
  - name: Install required packages
    yum:
      name: '{{ item }}'
      state: 'present'
    with_items:
      - epel-release
      - kernel-devel
      - dkms
      - "@development"

  - name: Setup Virtualbox repo
    copy: 
      src: files/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo


  - name: VirtualBox signing key
    rpm_key:
      key: "{{ virtualbox_repo_key }}"
      state: 'present'

  - name: Install VirtualBox
    yum:
      name: "VirtualBox-5.0"
      state: 'present'

  - name: Install vagrant and required libraries
    yum:
      name: '{{ item }}'
      state: 'present'
    with_items:
      - https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm
